### ISSUE TITLE
No commits by other team members

### ISSUE THREAD

**Issue by marksherman** [oplS16projects/Timeline-Thing#1]
The work done on Milestone 1 is acceptable, but it was entirely committed by @sv-uml.

I need to see each person doing their parts and committing to git directly. It's not just a turn-in system, it is a code control system that I need you to assimilate.

I need to see work done by @Onamar and @tturrell

**Comment by jswaz** [comment]
I'm not entirely sure what happened but I thought I definitely did a release later that night with significantly more work done, to replace the one posted by @sv-uml. Should I post it again? I don't think any major work has been done since that Friday otherwise.

**Comment by jswaz** [comment]
So the internet in University Suites is down right now and I can't actually make any changes to the master branch right now, but my branch is still here locally and the last changes made to anything on my end were definitely on Friday night. I made another fork of master for now to have as a backup, but what should my next step be?

**Comment by marksherman** [comment]
Next step will be to take your fork (which is NOT master, but a copy of
your master), and push it up to github so I can see. Let me know when it's
all working.

**Comment by jswaz** [comment]
I tried sending a pushing the recent copy I made of the master and it's saying "master and Timeline-What's-going-on are entirely different commit histories."

I tried pushing the branch I had done my work on, called "Timeline-JS", and I just get a validation error.

This was through the Github for windows application and not the command line, if that matters.

**Comment by sv-uml** [comment]
If it's okay with @marksherman, then @Onamar, I think you should start adding new stuff to the master branch in addition to investigating what went wrong the other day. Otherwise, the development of the frontend and backend will get unbalanced and cause delays in the future.

**Comment by marksherman** [comment]
That commit history is pretty boned. All the work was re-committed fresh at
some point, erasing the associated history. There are multiple unrelated
files in the same commits, everything has been squashed together.
Start from where you are, and do it right here out.

**Comment by jswaz** [comment]
Alright, thanks. Still not sure what happened but I'll do my best to avoid it happening again.

Oh, and @sv-uml I have been working on the database stuff a bit more already, I just haven't done any commits into the master branch until we get all of this sorted out.

**Comment by marksherman** [comment]
It's now Milestone 2, and I still no evidence of contribution from @Onamar nor @tturrell.

Please describe to me what your development process is. This can be over email.

**Comment by jswaz** [comment]
I'm still not sure what's going on. My commits are being credited on my end, and the files are changed on the repository, but the commits aren't being credited on the repository itself. Either I'm doing something wrong or it's a problem with the Github application. Next time I do some work on it I'll try doing my commits through the command line instead to see if that actually works.

EDIT: Wait nevermind I think I figured out what I was doing wrong. Probably.

**Comment by marksherman** [comment]
Make absolutely sure you're logged in as you in the app, and that nobody
ever uses -f.

**Comment by jswaz** [comment]
I've always been logged in as myself. Somehow I was updating the files in the repository without it counting as an actual commit. I figured out how to not do that though so my commits should appear normally now.
